# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

# steps:
# - task: Xcode@5
#   inputs:
#     actions: 'build'
#     scheme: ''
#     sdk: 'iphoneos'
#     configuration: 'Release'
#     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#     xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
jobs:
- job: ios_build
  displayName: iOS
  steps:
  - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'
  - task: FlutterBuild@0
    inputs:
      target: ios
      projectDirectory: ${Build.SourcesDirectory}
      iosCodesign: false
      # debugMode: ${{ parameters.debugMode }}
      profileMode: 'true'
      exportOptionsPlist: ${Build.SourcesDirectory}/ios/exportOptions.plist
      verboseMode: true
    displayName: Build (Flutter)
